# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imgs', models.CharField(max_length=300)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'mml_carousel',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imgs', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=50)),
                ('productnumber', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'mml_goods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('token', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mml_user',
            },
        ),
    ]
