# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='imgs',
            field=models.CharField(max_length=300),
        ),
    ]
