# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='isselect',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
