# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190113_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imgs', models.CharField(max_length=300)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'mml_goods',
            },
        ),
    ]
