# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goods_isselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='isselect',
            field=models.CharField(default='checked', max_length=10),
        ),
    ]
