# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190118_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='isselect',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
