# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190118_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
    ]
